engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
  apexmetrics:
    enabled: true
  reek:
    enabled: true

ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- db/**/*
- db_content/**/*
- 'lib/schema_revamp.rb' # excluding because it is a temporary migration script
