inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'
    - 'frontend/node_modules/**/*'
    - lib/schema_revamp.rb
    - app/controllers/api/v2/**/*
    - app/models/**/* # hard to exclude only old models because they're not namespaced
    - app/serializers/**/** # hard to exclude only old serializers because they're not namespaced
    - spec/controllers/api/v2/**/*
  Include:
    - app/models/api/v3/**/*
    - app/models/content/**/*
    - app/models/concerns/**/*
    - app/serializers/api/v3/**/*
    - app/serializers/content/**/*


Bundler/OrderedGems:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'

Style/AndOr:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassVars:
  Exclude:
    - 'app/models/api/v3/base_model.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets
